version: '3.8'
services:
  mongo:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  redis:
    image: redis:7.2-rc2
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data/db
